name: Compile & Lint Check

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
      - 'feature/**'
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarcloud:
    name: Compile & Lint Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: npm install
      
      - name: Lint and compile
        run: |
          npm run lint
          npm run compile